### ISSUE TITLE
Can't build on Mageia 4 x64

### ISSUE THREAD

**Issue by AngryPenguinPL** [ValveSoftware/voglperf#17]
Hi.
Im trying build Voglperf on my system but I have problem :/

[x@localhost voglperf (master)]$ make voglperf64

cmake options:
  -DCMAKE_BUILD_TYPE='Release': Build debug or release. (Debug|Release)
  -DCMAKE_VERBOSE='OFF': Spew cmake project options. (On|Off)
  -DBUILD_X64='True': Build 32 or 64-bit. (On|Off)

Building 64-bit voglperf...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/x/voglperf/build64
make[1]: Entering directory '/home/x/voglperf/build64'
make[2]: Entering directory '/home/x/voglperf/build64'
make[3]: Entering directory '/home/x/voglperf/build64'
make[3]: Leaving directory '/home/x/voglperf/build64'
make[3]: Entering directory '/home/x/voglperf/build64'
make[3]: **\* No rule to make target '/usr/lib64/libGL.so', required by '/home/x/voglperf/bin/libvoglperf64.so'. Stop.
make[3]: Leaving directory '/home/x/voglperf/build64'
CMakeFiles/Makefile2:63: commands for target 'CMakeFiles/voglperf.dir/all' failed
make[2]: **\* [CMakeFiles/voglperf.dir/all] error 2
make[2]: Leaving directory '/home/x/voglperf/build64'
Makefile:75: commands for target 'all' failed
make[1]: **\* [all] error 2
make[1]: Leaving directory '/home/x/voglperf/build64'
Makefile:19: commands for target 'voglperf64' failed
make: **\* [voglperf64] error 2
[x@localhost voglperf (master)]$ 

Its some about /libGL.so? Hmm i have installed fglrx driver and have default mesa pack - stock in my system but why this error present? BTW. sorry for bad english translation :)

**Comment by ProfessorKaos64** [comment]
Do you have all required packages? See my comment [here](https://github.com/ValveSoftware/voglperf/issues/19#issuecomment-87035823)
